# Generated by Django 4.1.6 on 2023-04-01 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_desc'),
        ('users', '0002_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
