# Generated by Django 4.1.6 on 2023-04-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
