# Generated by Django 4.1.6 on 2023-04-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
