# Generated by Django 4.1.6 on 2023-04-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_date_created_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
